### PR TITLE
Bump version to 0.7.1

### PR DESCRIPTION
**Pull request by MaxDesiatov**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@kateinoigakukun as far as I understand, only you have access to NPM deployments, so we can't upload the bugfix without you 🙂

**Review by j-f1 — APPROVED** [review]

**Comment by j-f1** [comment]
Oof, we should get automatic publishing set up for npm

**Review by kateinoigakukun — APPROVED** [review]

**Comment by kateinoigakukun** [comment]
@MaxDesiatov I'll invite you as a package owner. Please tell me your npm account name.

**Comment by MaxDesiatov** [comment]
@kateinoigakukun thanks! I'm `maxd` on npm.

**Pull request merged**
