### PR TITLE
Generate and publish documentation with `swift-doc`

### PR DESCRIPTION
**Pull request by MaxDesiatov**
You can see the deployment at https://swiftwasm.github.io/JavaScriptKit/.

I'll update the trigger to deploy only on pushes to `master` if you think this is something we should proceed with.

### CODE REVIEW

**Comment by j-f1** [comment]
Looks like there’s some cleanup necessary in the “functions” category — all of those should be private imo. It also doesn’t properly handle standard Swift types — is there a way to link those to developer.apple.com?

**Comment by MaxDesiatov** [comment]
I'll clean things up, but cross-module references unfortunately aren't supported in `swift-doc` yet 😔

**Comment by MaxDesiatov** [comment]
Everything seems to work when `@_cdecl` functions are made internal, so they are no longer displayed in the docs now.

**Review by kateinoigakukun — APPROVED** [review]
Nice!

**Pull request merged**
