### PR TITLE
Add Prettier, reformat JS code

### PR DESCRIPTION
**Pull request by j-f1**
See https://github.com/swiftwasm/JavaScriptKit/pull/68#discussion_r493470193. This introduces a bunch of changes so I wanted to pull it into a separate PR so we can bikeshed on options if necessary.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Could you also add `.pre-commit-config.yml` with a `prettier` snippet [as described here](https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit), and we could add SwiftFormat and SwiftLint to it in future PRs?

**Comment by j-f1** [comment]
I’m trying but it’s not working ¯\\\_(ツ)\_/¯

Screenshot_2020-09-23 19 43 30

it’s been like that for several minutes.

**Review by MaxDesiatov — APPROVED** [review]
LGTM 👍 I'll try to add `pre-commit` in a separate PR

**Review by kateinoigakukun — APPROVED** [review]

**Comment by j-f1** [comment]
Huh:

> Fatal error: invalid Collection: more than 'count' elements in collection: file Swift/ContiguousArrayBuffer.swift, line 727

**Pull request merged**
